Repository Leets-Makers/Leenk-BE, pull requests merged in 2025-08, with the labels that each got.

#47 LNK-BE-21 로그인 트리거 수정
  src/main/java/leets/leenk/domain/user/domain/entity/User.java
  src/main/java/leets/leenk/global/auth/application/usecase/AuthUsecase.java
Labels: ♻️Refactor

#54 LNK-BE-25 피드 수정
  src/main/java/leets/leenk/domain/feed/application/dto/request/FeedUpdateRequest.java
  src/main/java/leets/leenk/domain/feed/application/dto/request/FeedUploadRequest.java
  src/main/java/leets/leenk/domain/feed/application/exception/ErrorCode.java
  src/main/java/leets/leenk/domain/feed/application/exception/FeedUpdateNotAllowedException.java
  src/main/java/leets/leenk/domain/feed/application/usecase/FeedUsecase.java
  src/main/java/leets/leenk/domain/feed/domain/entity/Feed.java
  src/main/java/leets/leenk/domain/feed/domain/repository/LinkedUserRepository.java
  src/main/java/leets/leenk/domain/feed/domain/service/FeedUpdateService.java
  src/main/java/leets/leenk/domain/feed/domain/service/LinkedUserDeleteService.java
  src/main/java/leets/leenk/domain/feed/presentation/FeedController.java
  src/main/java/leets/leenk/domain/media/domain/repository/MediaRepository.java
  src/main/java/leets/leenk/domain/media/domain/service/MediaDeleteService.java
  src/main/java/leets/leenk/domain/notification/domain/repository/NotificationRepositoryImpl.java
Labels: ✨Feat

#59 LNK-BE-27 피드 설명 개행 제거
  src/main/java/leets/leenk/domain/feed/application/mapper/FeedMapper.java
  src/main/java/leets/leenk/domain/feed/application/util/FeedDescriptionUtil.java
  src/main/java/leets/leenk/domain/feed/domain/service/FeedUpdateService.java
Labels: ♻️Refactor

#63 LNK-BE-29 내가 참여한, 다른 사람이 참여한 링크 리스트 조회
  src/main/java/leets/leenk/domain/leenk/application/dto/response/LeenkDetailResponse.java
  src/main/java/leets/leenk/domain/leenk/application/mapper/LeenkMapper.java
  src/main/java/leets/leenk/domain/leenk/application/usecase/LeenkUsecase.java
  src/main/java/leets/leenk/domain/leenk/domain/repository/LeenkParticipantsRepository.java
  src/main/java/leets/leenk/domain/leenk/domain/service/LeenkParticipantsGetService.java
  src/main/java/leets/leenk/domain/leenk/presentation/LeenkController.java
  src/main/java/leets/leenk/domain/leenk/presentation/ResponseCode.java
Labels: ♻️Refactor, ✨Feat
